"""The contract's debt: each tool that does not keep a point yet, and the points (T04b).

The contract test (``test_tool_contract.py``) fails when a tool owes a point not listed here, and
when a tool keeps a point it still lists: the list only shrinks. Whoever migrates a module (T05 to
T09) deletes its tools' points and nothing else.

Initial size (2026-10-05): 121 tools; window 96, errors 91, not_found 22, zero 42, limits 70.
"""

from __future__ import annotations


def _owes(*points: str) -> frozenset[str]:
    return frozenset(points)


# Definitions of the copied cut helpers (``_truncate``, ``_trim``) left in ``toolkit/tools``.
CUT_HELPERS = 12

DEBT: dict[str, frozenset[str]] = {
    "air_quality_forecast": _owes("window", "limits"),
    "arxiv_paper": _owes("window", "errors", "not_found"),
    "arxiv_search": _owes("window", "errors", "zero", "limits"),
    "chembl_activity_search": _owes("window", "errors", "zero", "limits"),
    "chembl_molecule": _owes("errors"),
    "chembl_molecule_search": _owes("window", "errors", "zero", "limits"),
    "chembl_target": _owes("errors"),
    "chembl_target_search": _owes("window", "errors", "zero", "limits"),
    "clinical_trial_study": _owes("window", "errors"),
    "clinical_trials_search": _owes("window", "errors", "zero", "limits"),
    "country_info": _owes("errors", "not_found"),
    "crossref_search": _owes("window", "errors", "zero", "limits"),
    "crossref_work": _owes("window", "errors"),
    "csv_read": _owes("window", "limits"),
    "dailymed_label": _owes("window", "errors", "limits"),
    "dailymed_label_search": _owes("window", "errors", "zero", "limits"),
    "datacite_doi": _owes("window", "errors"),
    "datacite_search": _owes("window", "errors", "zero", "limits"),
    "date_add": _owes("limits"),
    "earthquake_count": _owes("errors"),
    "earthquake_event": _owes("errors"),
    "earthquake_search": _owes("window", "errors", "zero", "limits"),
    "eonet_categories": _owes("errors"),
    "eonet_event": _owes("window", "errors"),
    "eonet_events": _owes("window", "errors", "zero", "limits"),
    "europe_pmc_article": _owes("window", "errors", "not_found"),
    "europe_pmc_citations": _owes("window", "errors", "not_found", "limits"),
    "europe_pmc_search": _owes("window", "errors", "zero", "limits"),
    "eurostat_compare": _owes("window", "limits"),
    "eurostat_dataset": _owes("window"),
    "eurostat_dataset_search": _owes("window", "errors", "zero", "limits"),
    "eurostat_dimensions": _owes("window", "limits"),
    "eurostat_series": _owes("window", "limits"),
    "foodon_search": _owes("window", "errors", "zero", "limits"),
    "foodon_term": _owes("errors", "not_found"),
    "gbif_occurrence_search": _owes("window", "errors", "zero", "limits"),
    "gbif_species": _owes("errors"),
    "gbif_species_match": _owes("errors", "not_found"),
    "gbif_species_search": _owes("window", "errors", "zero", "limits"),
    "gdelt_news_search": _owes("window", "errors", "zero", "limits"),
    "gdelt_timeline": _owes("window", "errors", "zero"),
    "geocode": _owes("window", "errors", "zero"),
    "get_forecast": _owes("errors", "not_found", "limits"),
    "get_forecast_by_coords": _owes("errors", "limits"),
    "get_weather": _owes("errors", "not_found"),
    "get_weather_by_coords": _owes("errors"),
    "hacker_news": _owes("window", "errors", "limits"),
    "ip_lookup": _owes("errors"),
    "json_extract": _owes("not_found"),
    "list_directory": _owes("window"),
    "nvd_cve": _owes("window", "errors", "not_found"),
    "nvd_cve_search": _owes("window", "errors", "zero", "limits"),
    "open_food_facts_compare": _owes("window", "errors", "not_found"),
    "open_food_facts_nutrition": _owes("window", "errors", "not_found"),
    "open_food_facts_product": _owes("window", "errors", "not_found"),
    "open_food_facts_search": _owes("window", "errors", "zero", "limits"),
    "openfda_food_recall": _owes("errors"),
    "openfda_food_recall_search": _owes("window", "errors", "zero", "limits"),
    "osm_reverse_geocode": _owes("window", "errors", "limits"),
    "osm_search_place": _owes("window", "errors", "zero", "limits"),
    "overpass_pois": _owes("window", "errors", "zero", "limits"),
    "overpass_query": _owes("window", "errors", "zero", "limits"),
    "pdb_chemical_component": _owes("errors"),
    "pdb_entry": _owes("errors"),
    "pdb_ligands": _owes("errors"),
    "pdb_search": _owes("window", "errors", "zero", "limits"),
    "pubmed_article": _owes("window", "errors", "not_found"),
    "pubmed_search": _owes("window", "errors", "zero", "limits"),
    "read_file": _owes("window", "limits"),
    "regex_search": _owes("window", "zero"),
    "reverse_geocode": _owes("errors"),
    "ror_organization": _owes("window", "errors"),
    "ror_search": _owes("window", "errors", "zero", "limits"),
    "run_command": _owes("window", "limits"),
    "rxnorm_concept": _owes("errors"),
    "rxnorm_drug_search": _owes("window", "errors", "zero"),
    "rxnorm_ndcs": _owes("window", "errors"),
    "rxnorm_related": _owes("window", "errors", "limits"),
    "search_files": _owes("window", "zero", "limits"),
    "semantic_scholar_citations": _owes("window", "errors", "limits"),
    "semantic_scholar_paper": _owes("window", "errors"),
    "semantic_scholar_search": _owes("window", "errors", "zero", "limits"),
    "timezone_lookup": _owes("errors"),
    "uniprot_crossrefs": _owes("window", "limits"),
    "uniprot_entry": _owes("window"),
    "uniprot_features": _owes("window", "limits"),
    "uniprot_search": _owes("window", "zero", "limits"),
    "weather_units": _owes("errors"),
    "who_indicator": _owes("errors", "not_found"),
    "who_indicators": _owes("window", "errors", "zero", "limits"),
    "who_series": _owes("window", "errors", "limits"),
    "wikidata_entity": _owes("window", "errors"),
    "wikidata_search": _owes("window", "zero", "limits"),
    "wikidata_sparql": _owes("window", "errors", "zero", "limits"),
    "world_bank_compare": _owes("window", "errors", "not_found", "limits"),
    "world_bank_countries": _owes("window", "errors", "limits"),
    "world_bank_indicator": _owes("window", "errors"),
    "world_bank_indicators": _owes("window", "errors", "zero", "limits"),
    "world_bank_series": _owes("window", "errors", "not_found", "limits"),
    "world_bank_sources": _owes("window", "errors", "limits"),
    "world_bank_topics": _owes("window", "errors", "limits"),
}
