"""ai-arch-toolkit — Lightweight unified LLM client with agent architectures."""

from __future__ import annotations

from importlib.metadata import PackageNotFoundError, version

# --- Core primitives ---
from ai_arch_toolkit.core import (
    LLM,
    APIError,
    BatchRequest,
    BatchResult,
    CachePart,
    Citation,
    Content,
    ContentPart,
    DocumentPart,
    ImagePart,
    Middleware,
    OutputSchema,
    RateLimitError,
    Request,
    Response,
    RetryConfig,
    RichStreamResponse,
    ServerTool,
    StreamEvent,
    SyncRichStreamResponse,
    ThinkingBlock,
    ToolCall,
    ToolGroup,
    Usage,
    assistant,
    async_execute_tool,
    cache,
    code_execution,
    document,
    execute_tool,
    image,
    infer_schema,
    prepare_tools,
    pricing,
    system,
    tool,
    tool_result,
    user,
    web_search,
)

# --- Toolkit convenience ---
from ai_arch_toolkit.toolkit import (
    AgentConfig,
    AgentEvent,
    AgentResult,
    AgentStep,
    BaseAgent,
    BruteForceIndex,
    GraphBackend,
    GraphStore,
    LATSAgent,
    LATSConfig,
    LLMCompilerAgent,
    LLMCompilerConfig,
    MemoryMiddleware,
    MemoryPreset,
    Node,
    PhaseConfig,
    PlanExecuteAgent,
    PlanExecuteConfig,
    PropertyView,
    ReActAgent,
    ReflexionAgent,
    ReflexionConfig,
    RelationalView,
    ReWOOAgent,
    ReWOOConfig,
    SearchResult,
    SelfDiscoveryAgent,
    SelfDiscoveryConfig,
    SimilarityView,
    StopReason,
    TemporalView,
    ToTAgent,
    ToTConfig,
    VectorIndex,
    cognitive,
    conversational,
    memory_tools,
    run_tools,
    run_tools_sync,
)

try:
    __version__ = version("ai-arch-toolkit")
except PackageNotFoundError:
    __version__ = "0.0.0"

__all__ = [
    "LLM",
    "APIError",
    "AgentConfig",
    "AgentEvent",
    "AgentResult",
    "AgentStep",
    "BaseAgent",
    "BatchRequest",
    "BatchResult",
    "BruteForceIndex",
    "CachePart",
    "Citation",
    "Content",
    "ContentPart",
    "DocumentPart",
    "GraphBackend",
    "GraphStore",
    "ImagePart",
    "LATSAgent",
    "LATSConfig",
    "LLMCompilerAgent",
    "LLMCompilerConfig",
    "MemoryMiddleware",
    "MemoryPreset",
    "Middleware",
    "Node",
    "OutputSchema",
    "PhaseConfig",
    "PlanExecuteAgent",
    "PlanExecuteConfig",
    "PropertyView",
    "RateLimitError",
    "ReActAgent",
    "ReWOOAgent",
    "ReWOOConfig",
    "ReflexionAgent",
    "ReflexionConfig",
    "RelationalView",
    "Request",
    "Response",
    "RetryConfig",
    "RichStreamResponse",
    "SearchResult",
    "SelfDiscoveryAgent",
    "SelfDiscoveryConfig",
    "ServerTool",
    "SimilarityView",
    "StopReason",
    "StreamEvent",
    "SyncRichStreamResponse",
    "TemporalView",
    "ThinkingBlock",
    "ToTAgent",
    "ToTConfig",
    "ToolCall",
    "ToolGroup",
    "Usage",
    "VectorIndex",
    "__version__",
    "assistant",
    "async_execute_tool",
    "cache",
    "code_execution",
    "cognitive",
    "conversational",
    "document",
    "execute_tool",
    "image",
    "infer_schema",
    "memory_tools",
    "prepare_tools",
    "pricing",
    "run_tools",
    "run_tools_sync",
    "system",
    "tool",
    "tool_result",
    "user",
    "web_search",
]
